Feature/api tests
Kartman570/TaskManager pull request #11
Opened 2023-08-18 00:11 UTC by Kartman570

Ветки отделял каждую друг от друга, а не все от develop, что бы было проще проверять коммиты (раз заливаю их разом). Возможно это не очень корректно с точки зрения git-flow, но я посчитал что читаемость изменений важнее в данном случае

2023-08-21 07:01 UTC, aleksandr-semenov-dbp requested changes
Это довольно большое ключевое задание, здесь надо покрыть тестами все api то есть list, retrieve, update, delete для Task и Tag

2023-08-28 05:25 UTC, aleksandr-semenov-dbp requested changes

2023-08-28 05:25 UTC, aleksandr-semenov-dbp commented on main/views.py
> +    queryset = Task.objects.prefetch_related("tags", "author", "worker")#А ПРЕФЕТЧ ОТДАЕТ В ПРАВИЛЬНОМ ПОРЯДКЕ???
Порядок определяется order_by(). Для foreign key нужно использовать select_related() который полностью работает на уровне БД. Надо исправить модели чтобы задача могла иметь несколько тегов.

2023-08-28 05:25 UTC, aleksandr-semenov-dbp commented on test/base.py
> +        self.client.force_login(self.user)
Не понял по какому правилу используется то force_login() то force_authenticate()

2023-08-28 05:25 UTC, aleksandr-semenov-dbp commented on test/test_tag.py
> +        assert response == expected_response
мне кажется здесь перепутан код респонза и его тело. В случае удаления хорошо бы еще проверить что после него объекта не существует

2023-08-28 05:25 UTC, aleksandr-semenov-dbp commented on test/test_task.py
> +        assert now - timedelta(seconds=1) <= changed_date <= now + timedelta(seconds=1)
судя по повтору кода что-то надо выделить в отдельную функцию/метод

2023-08-30 12:22 UTC, Kartman570 commented on test/base.py
> +        return response
Так как некоторые запросы (list, retrieve, delete) могут возвращать пустые значения, ассерты убрал из базового файла, оставив только в файлах конкретных тестов. те уже будут сверять тело ответа с ожидаемым, без учета статуса http(кроме удаления).
засчет этого в последствии можно будет добавить тест например для проверки создания неподходящего юзера (ранее ассерт по умолчанию считал что должен быть только успех)

2023-09-08 13:46 UTC, kirill-gorshkov requested changes

2023-09-08 13:46 UTC, kirill-gorshkov commented on test/test_tag.py
> +        assert new_response.status_code == HTTPStatus.NOT_FOUND
После удаления не обязательно проверять базу на наличие записи

2023-09-08 13:46 UTC, kirill-gorshkov commented on test/test_tag.py
> +        expected_response = tags_list
tags_list лучше сразу назвать expected_response или expected_tag_list, чтобы не определять переменную зазря.
Небольшой лайфхак, если в for-loop'е переменная не планирует использоваться, то лучше сразу писать `for _ in range(5)`.

2023-09-08 13:46 UTC, kirill-gorshkov commented on test/test_tag.py
> +            tags_list.append(tag.data)
Если какая-то конструкция используется неоднократно, то имеет смысл вынести ее в отдельную функцию. 
`def _create_expected_data()`, например.

2023-09-08 13:46 UTC, kirill-gorshkov commented on test/test_tag.py
> +        response = self.retrieve(tags_list[2]["id"])
Для проверки работоспособности GET'а совсем не обязательно создавать несколько сущностей, если, конечно, не проверяется фильтрация. Тут будет достаточно одной записи.

2023-09-08 13:46 UTC, kirill-gorshkov commented on test/test_task.py
> +        assert self.is_auto_date_time_correct(response.data["changed_date"])
Мы не проверяем валидность даты таким способом. Вместо этого лучше всего использовать библиотку [freezegun](https://github.com/spulec/freezegun), которая позволит точно указать нужный таймстамп, а потом докинуть его в expected_respone

2023-09-08 13:46 UTC, kirill-gorshkov commented on test/test_task.py
> +        del response.data["changed_date"]
Удалять данные из полученеого результата некорректно, так как это меняет ожидамое поведение какой-либо структуры. Предположим, что кто-то где-то удалил `response.data["name"]`. Хорошо, если это заметно, а если это в базовом классе? 

Если нужна новая структура, то лучше всего сделать копию, а уже в копии что-то менять.
`copied_repsonse = deepcopy(response.data)`

2023-09-08 13:46 UTC, kirill-gorshkov commented on test/test_task.py
> +        assert response.data == expected_response
task в данном случае не task, а response. Если хочется получить именно task, то лучше написать `task = response.data`

2023-09-08 16:51 UTC, Kartman570 commented on test/test_tag.py
> +        assert new_response.status_code == HTTPStatus.NOT_FOUND
в прошлых проверках рекомендовали проверить выполнилось ли удаление на самом деле из самой базы. так как операция не накладная, но может выявить ошибку в методе, решил оставить в следующем комите

2023-09-09 20:40 UTC, aleksandr-semenov-dbp approved these changes

2023-09-11 19:05 UTC, merged