Feature/filters and serializations
Kartman570/TaskManager pull request #7
Opened 2023-08-18 00:09 UTC by Kartman570

Ветки отделял каждую друг от друга, а не все от develop, что бы было проще проверять коммиты (раз заливаю их разом). Возможно это не очень корректно с точки зрения git-flow, но я посчитал что читаемость изменений важнее в данном случае

2023-08-21 06:49 UTC, aleksandr-semenov-dbp requested changes

2023-08-21 06:49 UTC, aleksandr-semenov-dbp commented on main/views.py
> +    serializer_class = TagSerializer
Тут стоит применить select_related и prefetch_related как упоминается в задании

2023-08-28 04:42 UTC, aleksandr-semenov-dbp requested changes

2023-08-28 04:42 UTC, aleksandr-semenov-dbp commented on main/views.py
> +    queryset = Task.objects.select_related("tags", "author", "worker").all()
На этом этапе вижу что неправильно сделано поле tags, у каждой задачи должно быть несколько тегов

2023-09-01 19:30 UTC, aleksandr-semenov-dbp requested changes

2023-09-01 19:30 UTC, aleksandr-semenov-dbp commented on main/views.py
> +    queryset = Task.objects.select_related("tags", "author", "worker").all()
select_related() не работает с many2many

2023-09-08 13:28 UTC, kirill-gorshkov approved these changes

2023-09-11 19:13 UTC, merged