added permissions and is_staff
Kartman570/TaskManager pull request #9
Opened 2023-08-18 00:10 UTC by Kartman570

Ветки отделял каждую друг от друга, а не все от develop, что бы было проще проверять коммиты (раз заливаю их разом). Возможно это не очень корректно с точки зрения git-flow, но я посчитал что читаемость изменений важнее в данном случае

2023-08-21 06:51 UTC, aleksandr-semenov-dbp requested changes

2023-08-21 06:51 UTC, aleksandr-semenov-dbp commented on main/permissions.py
> +        return obj.owner == request.user
Это не то, про что написано в задании и названии этого класса

2023-08-28 04:47 UTC, aleksandr-semenov-dbp requested changes

2023-08-28 04:47 UTC, aleksandr-semenov-dbp commented on main/models/user.py
> +    is_staff = models.BooleanField(default=False)
Не нужно создавать это поле, оно есть у встроенного Джанго-юзера

2023-08-28 04:47 UTC, aleksandr-semenov-dbp commented on main/permissions.py
> +    def has_object_permission(self, request, view, obj):
В данном случае нужно проверять доступ не к конкретным объектам а использование методов

2023-08-28 04:47 UTC, aleksandr-semenov-dbp commented on main/permissions.py
> +        return request.user.is_staff
В задании речь шла только об удалении, такой перемешен запретит любое изменение не-стаффом.

2023-09-08 13:48 UTC, kirill-gorshkov requested changes

2023-09-08 13:48 UTC, kirill-gorshkov commented on main/permissions.py
> +            return True
В данном случае else не несет никакой смысловой нагрузки, лучше его убрать

2023-09-09 20:36 UTC, aleksandr-semenov-dbp requested changes

2023-09-09 20:36 UTC, aleksandr-semenov-dbp commented on main/permissions.py
> +class IsStaffOrReadOnly(permissions.BasePermission):
Не очень удачное название класса, мы все же делаем не ридонли, а только запрещаем удалять

2023-09-09 20:36 UTC, aleksandr-semenov-dbp commented on main/views.py
> +    permission_classes = [IsStaffOrReadOnly]
здесь можно (и логично) совмещать перемешены `permission_classes = [IsStaffOrReadOnly, IsAuthenticated]`

2023-09-11 16:50 UTC, aleksandr-semenov-dbp approved these changes

2023-09-11 19:10 UTC, merged